* Recuperação - Front End II
Aluno: Carlos Alberto S. S. Filho
Turma: T10

Para efeitos deste trabalho escolhi usar a seguinte API
+ https://thecatapi.com/

** Instruções e requisitos do entregáveis
1. O tema da aplicação é de sua preferência. Pode ser sobre qualquer uma das apis citadas abaixo:
+ https://codeboost.com.br/projetos/pokeapi/
+ https://jsonplaceholder.typicode.com/
+ https://randomuser.me/
+ https://thecatapi.com/
+ https://dog.ceo/dog-api/
+ https://fakestoreapi.com/docs
2. Você deve selecionar um endpoint que vai listar vários itens. Um exemplo seria um endpoint onde é listado todos os produtos de uma loja.
3. Salvar o retorno desse endpoint no localstorage.
4. Exibir essa lista no HTML a partir do localstorage.
5. Utilizar um ícone (pode ser uma lixeira) para cada item da lista, onde quando clicado, o item será removido do localstorage e a lista que está sendo exibida, será atualizada sem o item removido.

** SOBRE A ENTREGA
1. Trabalho individualmente, mas o aluno pode consultar material.
2. Prazo para o envio: 
   + Dia 03/05/2022 até às 23h59.
3. Devem ser entregues os arquivos HTML5, CSS3 e Javascript do projeto via formulário.
   + Você deverá enviar o link do repositório para este formulário: 
https://forms.gle/XgGgwBv5Rx2i2s3w7
